/**
 * Catalog contract, shared with product-service (single source of truth in
 * @market/types). Re-exported here so UI code keeps short local imports.
 */
export {
  AvailabilitySchema,
  BadgeSchema,
  CategorySchema,
  ConfigurationQuoteSchema,
  ConfiguratorSchema,
  FacetSchema,
  KEYBOARD_LAYOUTS,
  KeyboardLayoutSchema,
  PRODUCT_KINDS,
  ProductKindSchema,
  ProductListingSchema,
  ProductPreviewSchema,
  ProductSchema,
  ProductSummarySchema,
  ReviewSchema,
  SORT_OPTIONS,
  VariantSchema,
  type Availability,
  type Badge,
  type Category,
  type ConfigurationQuote,
  type ConfigurationSelection,
  type Configurator,
  type ConfiguratorGroup,
  type Facet,
  type KeyboardLayout,
  type Product,
  type ProductImage,
  type ProductKind,
  type ProductListing,
  type ProductOption,
  type ProductPreview,
  type ProductSummary,
  type Review,
  type SortOption,
  type Variant,
} from '@market/types';
