import { fileURLToPath } from 'node:url';
import { sql } from 'drizzle-orm';
import { drizzle } from 'drizzle-orm/node-postgres';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import type { PgDatabase, PgQueryResultHKT } from 'drizzle-orm/pg-core';
import pg from 'pg';
import * as schema from './schema.js';

/**
 * Driver-agnostic database handle: node-postgres in every environment, PGlite
 * (in-process Postgres) in tests. Repositories depend only on this type.
 */
export type Database = PgDatabase<PgQueryResultHKT, typeof schema>;

export const DATABASE = Symbol('DATABASE');

/** SQL migrations generated by drizzle-kit, shipped next to the compiled code. */
export const MIGRATIONS_FOLDER = fileURLToPath(new URL('../../drizzle', import.meta.url));

export interface PostgresConnection {
  db: Database;
  close: () => Promise<void>;
  ping: () => Promise<void>;
}

export function connectPostgres(url: string, maxConnections: number): PostgresConnection {
  const pool = new pg.Pool({
    connectionString: url,
    max: maxConnections,
    idleTimeoutMillis: 30_000,
    connectionTimeoutMillis: 5_000,
    // Bound runaway queries; individual queries can still SET LOCAL a different value.
    statement_timeout: 10_000,
    application_name: 'auth-service',
  });
  const db = drizzle(pool, { schema });
  return {
    db,
    close: () => pool.end(),
    ping: async () => {
      await db.execute(sql`select 1`);
    },
  };
}

export async function runMigrations(url: string): Promise<void> {
  const pool = new pg.Pool({ connectionString: url, max: 1 });
  try {
    await migrate(drizzle(pool), { migrationsFolder: MIGRATIONS_FOLDER });
  } finally {
    await pool.end();
  }
}
